# Generated by Django 4.0.2 on 2022-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0007_alter_company_address_alter_company_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
