# Generated by Django 4.0.2 on 2022-03-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0014_alter_user_is_customer_alter_user_is_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='binding_style',
            new_name='binding',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='circulation',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='final_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='final_width',
            new_name='pages_in_block',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='num_pages_in_block',
            new_name='pages_in_cover',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='num_pages_in_cover',
            new_name='pages_in_insert',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='num_pages_in_insert',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
