# Generated by Django 4.0.2 on 2022-03-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0015_rename_binding_style_order_binding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='circulation',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pages_in_block',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pages_in_cover',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pages_in_insert',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='width',
            field=models.IntegerField(blank=True),
        ),
    ]
