# Generated by Django 4.0.2 on 2022-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0016_alter_order_circulation_alter_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='density',
            field=models.IntegerField(choices=[('80', '80'), ('120', '120'), ('150', '150'), ('200', '200'), ('250', '250')]),
        ),
    ]
