# Generated by Django 4.0.2 on 2022-03-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0017_alter_paper_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pages_in_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pages_in_cover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pages_in_insert',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_insert',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='insert_paper', to='printery.paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='density',
            field=models.IntegerField(choices=[(80, '80 gr/m2'), (120, '120 gr/m2'), (150, '150 gr/m2'), (200, '200 gr/m2'), (250, '250 gr/m2')]),
        ),
    ]
