# Generated by Django 4.0.2 on 2022-03-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0018_alter_order_pages_in_block_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
