# Generated by Django 4.0.2 on 2022-03-20 15:10

from django.db import migrations, models
import printery.models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0020_remove_order_id_alter_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default='0', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=printery.models.Order.counter, unique=True),
        ),
    ]
