# Generated by Django 4.0.2 on 2022-03-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0026_remove_order_owner_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='order', to='printery.Order'),
        ),
    ]
