# Generated by Django 4.0.2 on 2022-02-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0005_user_is_employee_user_is_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Employee',
            new_name='is_employee',
        ),
    ]
