# Generated by Django 4.0.2 on 2022-08-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0005_order_due_date_alter_order_type_alter_paper_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(blank=True, choices=[('BLO', 'Block'), ('COV', 'Cover'), ('INS', 'Insert')], max_length=3),
        ),
    ]
