# Generated by Django 4.0.2 on 2022-09-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0007_alter_order_delivery_date_alter_order_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printdate', models.DateTimeField(blank=True, null=True)),
                ('day', models.BooleanField(default=True)),
                ('night', models.BooleanField(default=False)),
                ('circulation', models.IntegerField(blank=True, null=True)),
                ('platesisdone', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printery.order')),
            ],
        ),
    ]
