# Generated by Django 4.0.2 on 2022-09-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0008_printing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printery.order', to_field='number'),
        ),
    ]
