# Generated by Django 4.0.2 on 2022-09-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0009_alter_printing_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printing',
            name='order',
        ),
    ]
