# Generated by Django 4.0.2 on 2022-09-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0011_printing_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='printdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
