# Generated by Django 4.0.2 on 2022-09-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0012_alter_printing_printdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printing',
            old_name='platesisdone',
            new_name='plates_is_done',
        ),
        migrations.RenameField(
            model_name='printing',
            old_name='printdate',
            new_name='print_date',
        ),
    ]
