# Generated by Django 4.0.2 on 2022-09-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0013_rename_platesisdone_printing_plates_is_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printing',
            name='id',
        ),
        migrations.AlterField(
            model_name='printing',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='printery.order'),
        ),
    ]
