# Generated by Django 4.0.2 on 2022-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0014_remove_printing_id_alter_printing_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='density',
            field=models.IntegerField(choices=[(80, '80 gr/m2'), (100, '100 gr/m2'), (105, '105 gr/m2'), (115, '115 gr/m2'), (120, '120 gr/m2'), (150, '150 gr/m2'), (170, '170 gr/m2'), (200, '200 gr/m2'), (250, '250 gr/m2')]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='type',
            field=models.CharField(choices=[(None, 'Select...'), ('GL', 'Glossy'), ('MAT', 'Matte'), ('SIL', 'Silk'), ('OFF', 'Offset')], max_length=3),
        ),
        migrations.AlterField(
            model_name='part',
            name='color',
            field=models.CharField(blank=True, choices=[(None, 'Select...'), ('4_4', '4(CMYK)+4(CMYK)'), ('4_0', '4(CMYK)+0'), ('1_1', '1(Black)+1(Black)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='part',
            name='pages',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
