# Generated by Django 4.0.2 on 2022-03-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='owners',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='order',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_paper', to='printery.paper'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_paper', to='printery.paper'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_insert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insert_paper', to='printery.paper'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
