# Generated by Django 4.0.2 on 2022-03-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
