# Generated by Django 4.0.2 on 2022-03-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='owners',
            new_name='owner',
        ),
    ]
