# Generated by Django 4.0.2 on 2022-03-29 16:00

from django.db import migrations, models
import printery.models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=printery.models.Order.counter, unique=True),
        ),
    ]
