# Generated by Django 4.0.2 on 2022-03-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0002_alter_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='name',
            new_name='part_name',
        ),
    ]
