# Generated by Django 4.0.2 on 2022-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='circulation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
