# Generated by Django 4.0.2 on 2022-03-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0002_alter_order_circulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[(None, ''), ('BK', 'Book'), ('CL', 'Calendar'), ('MZ', 'Magazine'), ('NP', 'Newspaper'), ('FL', 'Flyers')], max_length=2),
        ),
    ]
