# Generated by Django 4.0.2 on 2022-03-27 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0003_alter_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='binding',
            field=models.CharField(blank=True, choices=[(None, 'Select...'), ('GLU', 'Glue'), ('STA', 'Staple'), ('HAR', 'Hardcover'), ('FOL', 'Folding')], max_length=4),
        ),
    ]
