# Generated by Django 4.0.2 on 2022-03-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0005_remove_order_pages_in_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_order', to='printery.part'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_order', to='printery.part'),
        ),
        migrations.AlterField(
            model_name='order',
            name='insert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insert_order', to='printery.part'),
        ),
    ]
