# Generated by Django 4.0.2 on 2022-03-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='laminat',
            new_name='laminate',
        ),
    ]
