# Generated by Django 4.0.2 on 2022-03-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='id_order',
            new_name='order',
        ),
    ]
