# Generated by Django 4.0.2 on 2022-09-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0013_rename_platesisdone_printing_plates_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printery.order', to_field='number', unique=True),
        ),
    ]
