# Generated by Django 4.0.2 on 2022-09-30 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0014_alter_printing_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printing',
            name='id',
        ),
        migrations.AlterField(
            model_name='printing',
            name='order',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='printery.order'),
            preserve_default=False,
        ),
    ]
